### ISSUE TITLE
uvicorn 0.19.0 移除了debug选项导致不兼容

### ISSUE THREAD

**Issue by Sunshine40** [NekoRabi/Majsoul-QQBot#4]
根据uvicorn更新日志

[Version 0.19.0](https://github.com/encode/uvicorn/releases/tag/0.19.0)
...
Removed
Remove the --debug flag (https://github.com/encode/uvicorn/pull/1640) 14/09/22
Remove the DebugMiddleware (https://github.com/encode/uvicorn/pull/1697) 07/10/22

现在通过pip快速安装依赖后，运行main.py会产生如下错误：

Traceback (most recent call last):
  File "&lt;path-to-project&gt;\Majsoul-QQBot\main.py", line 66, in <module>
    bot.run(port=17580)
  File "&lt;path-to-site-packages&gt;\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "&lt;path-to-site-packages&gt;\mirai\bot.py", line 255, in run
    if not asgi_serve(
  File "&lt;path-to-site-packages&gt;\mirai\asgi.py", line 205, in asgi_serve
    run(app, host=host, port=port, debug=True, **kwargs)
TypeError: run() got an unexpected keyword argument 'debug'

改下requirements.txt的事，我就不提Pull Request了

**Comment by NekoRabi** [comment]
谢谢提醒，已将版本固定为 0.17.6
